# Site settings
title: Pierce's Paw Paradise
email: your-email@example.com
description: > 
  Test desc.
baseurl: ""  # For GitHub Pages
url: "https://pawparadise.github.io"

# Company Information
company_name: Pierce's Paw Paradise
address_line: Your Address Here
telephone_number: Your Phone Number
fax_number: Your Fax Number
company_email: your-email@example.com
google_map: https://www.google.com/maps/embed?...

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed